### ISSUE TITLE
Mesh import crashes studio..?

### ISSUE THREAD

**Issue by Wunder-Wulfe** [Roblox/avatar-evolution#18]
I tried to import a couple of my models (both of which were under 60k polygons) and both models had crashed my studio after giving me a blank error that tells me to go the mesh import troubleshooting article (while still successfully uploading to roblox)

**Comment by Wunder-Wulfe** [comment]
This is also on par with an issue that literally immediately crashes studio when importing with the avatar rig importer

**Comment by Wunder-Wulfe** [comment]
https://i.gyazo.com/68dd07e96a94422e8a8a2f3b42c95423.mp4

**Comment by Bladster94** [comment]
Encountered this issue too when trying to do the same manipulation with one of our own models rigged using Blender. However, it crashes only when the model has multiple parts: it doesn't crash when the mesh is one single part, even with bones. So I think it's something to do with having multiple parts.

**Comment by Bladster94** [comment]
To add information on the bug: it does not happen immediately once we try the importation, it seems to manage to upload the assets before crashing.

![image](https://user-images.githubusercontent.com/15011834/71939628-a081f580-31b3-11ea-8d79-5c2176ee9477.png)

Also, I noticed that a few odd axis "arrows" randomly appear at the very moment of the crash, after uploading the assets. The place used for the experience was nothing but a fresh new baseplate.

![image](https://user-images.githubusercontent.com/15011834/71939698-d921cf00-31b3-11ea-8eb5-67bf008b93b7.png)

So I assume that the crash happens after the asset upload, during an operation that only happens when there is more than one part. Hope this helps solving the issue, as this feature would drastically boost the animation potential of many games, including mine.

**Comment by adrianlongland** [comment]
@Wunder-Wulfe and @Bladster94 Multi part import should be fixed with the next beta release.

**Comment by Bladster94** [comment]
Update after having tried the latest beta release: it still crashes, but the behavior changed. Same model, same method, same conditions.

![image](https://user-images.githubusercontent.com/15011834/74271254-d9f6d500-4d0c-11ea-87ed-3bf30d51d98a.png)

The console says that the import has succeeded, but something absolutely gigantic seems to spawn, and about half a second later the game crashes. I tried many different angles and zooms during that half of a second, but never managed to see anything in that colossal area. I at least note the grey square which means the model has a primary part which isn't oversized.

So I have 2 theories: either the parts are imported with a size higher than what Studios is supposed to allow for and causes a crash, or the parts spawn at a very high distance from each other that somehow messes something up, probably confusion regarding the bones being misplaced, I don't know.

I will try messing with the model's size to see if it changes anything, but I don't think it will considering this model has been imported before and only was a dozen studs tall then (before we gave it bones and everything)

**Comment by adrianlongland** [comment]
Can you share the .fbx file, so I can debug?

**Comment by Bladster94** [comment]
Sure thing, here it is. It should be very easy to replicate, just create or open any place, import it as custom, and it crashes.

[TestWingRig.zip](https://github.com/Roblox/avatar-evolution/files/4194524/TestWingRig.zip)

**Comment by adrianlongland** [comment]
![image](https://user-images.githubusercontent.com/58868029/74386368-905cc780-4daa-11ea-863f-aa587b3a0d66.png)

**Comment by adrianlongland** [comment]
There is a bug in the current Beta Release where if the mesh does not have a texture, and one of the 'box mapped' sides doesn't have any triangles it will crash.
This will be fixed in the next release, which I will ask to get expatiated.
In the short term, putting a texture on it should fix it.

**Comment by Wunder-Wulfe** [comment]
Here is one of most simplest things to import yet it crashes studio for completely unknown reasons...


[untitled.zip](https://github.com/Roblox/avatar-evolution/files/4240686/untitled.zip)

**Comment by Bladster94** [comment]
@Wunder-Wulfe it doesn't seem to have a texture either, so it could be the same issue. Maybe if you added one it would work.

**Comment by adrianlongland** [comment]
@Wunder-Wulfe 
I tested your untitled.fbx with the latest internal build and it comes in fine - so you should be good once the next beta build is Released.
![image](https://user-images.githubusercontent.com/58868029/75198695-16b3ca80-5716-11ea-83b3-0d960762a0e0.png)

**Comment by Bladster94** [comment]
Yup, I tested my wing on the broken build and the import succeeded. Though it still was way too big for some unknown reason, and the animator behaved strangely, but I'm guessing it's just what happens with broken builds.

**Comment by Wunder-Wulfe** [comment]
@adrianlongland ok thanks, let me know when a new release comes out please
